packages:
  # all packages in subdirs of packages/ and components/
  - 'workspace-a'
  - 'workspace-b'
  - 'shared/*'
  - 'utils/**/'
  # exclude packages that are inside test directories
  - '!**/tests/**'
